apiVersion: v1
kind: Service  
metadata:
  name:  headless-udp
spec:
  selector:
    deployment: statefulset-udp-server
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  ports:
    - protocol: UDP
      port: 12000
      targetPort: 12000