apiVersion: v1
kind: Template
metadata:
  name: headless-udp 
  annotations:
    description: "UDP server is sample for headless service on OpenShift/kubernetes."
    iconClass: "icon-python"
    tags: ""
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    name: udp-server
  spec:
    containers:
    - env:
      - name: REDIS_PASSWORD
        value: ${REDIS_PASSWORD}
      image: dockerfile/redis
      name: master
      ports:
      - containerPort: 12000
        protocol: UDP
parameters:
- description: Password used for Redis authentication
  from: '[A-Z0-9]{8}'
  generate: expression
  name: REDIS_PASSWORD
labels:
  redis: master